networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    networks:
      - dev
    depends_on:
      - common_db

  common_db:
    image: postgres:14.15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - dev

volumes:
  postgres-data:
